/**
 * Action Types para el Store Global
 * Siguiendo el patrón Flux/Redux para flujo unidireccional de datos
 */

// Auth Actions
export const AUTH_ACTIONS = {
  LOGIN: 'AUTH/LOGIN',
  LOGOUT: 'AUTH/LOGOUT',
  SET_USER: 'AUTH/SET_USER',
  SET_LOADING: 'AUTH/SET_LOADING',
  SET_ERROR: 'AUTH/SET_ERROR',
};

// Vehicle Actions
export const VEHICLE_ACTIONS = {
  SET_VEHICLES: 'VEHICLES/SET_VEHICLES',
  ADD_VEHICLE: 'VEHICLES/ADD_VEHICLE',
  UPDATE_VEHICLE: 'VEHICLES/UPDATE_VEHICLE',
  DELETE_VEHICLE: 'VEHICLES/DELETE_VEHICLE',
  SET_LOADING: 'VEHICLES/SET_LOADING',
  SET_ERROR: 'VEHICLES/SET_ERROR',
  FILTER_VEHICLES: 'VEHICLES/FILTER_VEHICLES',
};

// Driver Actions
export const DRIVER_ACTIONS = {
  SET_DRIVERS: 'DRIVERS/SET_DRIVERS',
  ADD_DRIVER: 'DRIVERS/ADD_DRIVER',
  UPDATE_DRIVER: 'DRIVERS/UPDATE_DRIVER',
  DELETE_DRIVER: 'DRIVERS/DELETE_DRIVER',
  SET_LOADING: 'DRIVERS/SET_LOADING',
  SET_ERROR: 'DRIVERS/SET_ERROR',
};

// Maintenance Actions
export const MAINTENANCE_ACTIONS = {
  SET_ORDERS: 'MAINTENANCE/SET_ORDERS',
  ADD_ORDER: 'MAINTENANCE/ADD_ORDER',
  UPDATE_ORDER: 'MAINTENANCE/UPDATE_ORDER',
  DELETE_ORDER: 'MAINTENANCE/DELETE_ORDER',
  SET_FILTERS: 'MAINTENANCE/SET_FILTERS',
  SET_LOADING: 'MAINTENANCE/SET_LOADING',
  SET_ERROR: 'MAINTENANCE/SET_ERROR',
};

// Alert Actions
export const ALERT_ACTIONS = {
  SET_ALERTS: 'ALERTS/SET_ALERTS',
  ADD_ALERT: 'ALERTS/ADD_ALERT',
  DISMISS_ALERT: 'ALERTS/DISMISS_ALERT',
  CLEAR_ALERTS: 'ALERTS/CLEAR_ALERTS',
};

// UI Actions
export const UI_ACTIONS = {
  TOGGLE_SIDEBAR: 'UI/TOGGLE_SIDEBAR',
  SET_THEME: 'UI/SET_THEME',
  SET_NOTIFICATION: 'UI/SET_NOTIFICATION',
};
